vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|14 Feb 2005 07:28:44 -0000
vti_extenderversion:SR|6.0.2.5516
vti_author:SR|UBNDQ10\\Administrator
vti_modifiedby:SR|UBNDQ10\\Administrator
vti_timecreated:TR|14 Feb 2005 07:28:44 -0000
vti_cacheddtm:TX|14 Feb 2005 07:28:44 -0000
vti_filesize:IR|22336
vti_cachedtitle:SR|Dang ky lich cong tac tuan
vti_cachedbodystyle:SR|<body text="#000000"  topmargin=0 leftmargin=0   background=Images/bg.gif onload="dynAnimation()">
vti_cachedlinkinfo:VX|Q|inc/portal.css S|inc/common.js S|inc/animate.js S|inc/popcalendar.js S|Images/bg.gif A|CAL_WEEK_Waitapprove.ASP S|images\\\\text_DuyetLich.gif S|Images/bg.gif H|javascript:AddNew('<%=DateValueVN(curDate)%>','<%=rs("BookType_ID")%>'); S|images\\\\CAL_Week_New.gif H|javascript:history.back(-1); S|images/back.gif H|javascript:inbaocao('<%=DateValueVN(WeekFrom)%>','<%=lich%>','<%=strLocationID%>','<%=strChairManID%>') S|images/print.gif H|javascript:scrollWeek(-1) S|images/Prev_Button.gif S|images/Prev_Button_Over.jpg H|javascript:scrollWeek(1) S|images/Next_Button.gif S|images/Next_Button_Over.jpg S|images\\\\button_calendar.gif H|javascript:Edit('<%=p_BookID%>'); S|images\\\\edit.gif H|javascript:Delete('<%=p_BookID%>'); S|images\\\\del.gif H|javascript:Edit('<%=p_BookID%>'); S|images\\\\edit.gif H|javascript:Delete('<%=p_BookID%>'); S|images\\\\del.gif H|javascript:Approve('<%=p_BookID%>'); S|images\\\\Duyet.jpg H|javascript:NotApprove('<%=p_BookID%>'); S|images\\\\KhongDuyet.gif H|javascript:Postponse('<%=p_BookID%>'); S|images\\\\DoiHop.gif H|javascript:setOrder('<%=p_BookID%>','<%=p_curPos%>','up'); S|images\\\\order_up.gif H|javascript:setOrder('<%=p_BookID%>','<%=p_curPos%>','down'); S|images\\\\order_down.gif
vti_cachedsvcrellinks:VX|FQUS|WEBNOIBO/Source/LICHCONGTAC/inc/portal.css FSUS|WEBNOIBO/Source/LICHCONGTAC/inc/common.js FSUS|WEBNOIBO/Source/LICHCONGTAC/inc/animate.js FSUS|WEBNOIBO/Source/LICHCONGTAC/inc/popcalendar.js FSUS|WEBNOIBO/Source/LICHCONGTAC/Images/bg.gif FAUS|WEBNOIBO/Source/LICHCONGTAC/CAL_WEEK_Waitapprove.ASP NSUS|file:///N:/WWW/WEBNOIBO/Source/LICHCONGTAC/images\\\\text_DuyetLich.gif FSUS|WEBNOIBO/Source/LICHCONGTAC/Images/bg.gif SHUS|javascript:AddNew('<%=DateValueVN(curDate)%>','<%=rs("BookType_ID")%>'); NSUS|file:///N:/WWW/WEBNOIBO/Source/LICHCONGTAC/images\\\\CAL_Week_New.gif SHUS|javascript:history.back(-1); FSUS|WEBNOIBO/Source/LICHCONGTAC/images/back.gif SHUS|javascript:inbaocao('<%=DateValueVN(WeekFrom)%>','<%=lich%>','<%=strLocationID%>','<%=strChairManID%>') FSUS|WEBNOIBO/Source/LICHCONGTAC/images/print.gif SHUS|javascript:scrollWeek(-1) FSUS|WEBNOIBO/Source/LICHCONGTAC/images/Prev_Button.gif FSUS|WEBNOIBO/Source/LICHCONGTAC/images/Prev_Button_Over.jpg SHUS|javascript:scrollWeek(1) FSUS|WEBNOIBO/Source/LICHCONGTAC/images/Next_Button.gif FSUS|WEBNOIBO/Source/LICHCONGTAC/images/Next_Button_Over.jpg NSUS|file:///N:/WWW/WEBNOIBO/Source/LICHCONGTAC/images\\\\button_calendar.gif SHUS|javascript:Edit('<%=p_BookID%>'); NSUS|file:///N:/WWW/WEBNOIBO/Source/LICHCONGTAC/images\\\\edit.gif SHUS|javascript:Delete('<%=p_BookID%>'); NSUS|file:///N:/WWW/WEBNOIBO/Source/LICHCONGTAC/images\\\\del.gif SHUS|javascript:Edit('<%=p_BookID%>'); NSUS|file:///N:/WWW/WEBNOIBO/Source/LICHCONGTAC/images\\\\edit.gif SHUS|javascript:Delete('<%=p_BookID%>'); NSUS|file:///N:/WWW/WEBNOIBO/Source/LICHCONGTAC/images\\\\del.gif SHUS|javascript:Approve('<%=p_BookID%>'); NSUS|file:///N:/WWW/WEBNOIBO/Source/LICHCONGTAC/images\\\\Duyet.jpg SHUS|javascript:NotApprove('<%=p_BookID%>'); NSUS|file:///N:/WWW/WEBNOIBO/Source/LICHCONGTAC/images\\\\KhongDuyet.gif SHUS|javascript:Postponse('<%=p_BookID%>'); NSUS|file:///N:/WWW/WEBNOIBO/Source/LICHCONGTAC/images\\\\DoiHop.gif SHUS|javascript:setOrder('<%=p_BookID%>','<%=p_curPos%>','up'); NSUS|file:///N:/WWW/WEBNOIBO/Source/LICHCONGTAC/images\\\\order_up.gif SHUS|javascript:setOrder('<%=p_BookID%>','<%=p_curPos%>','down'); NSUS|file:///N:/WWW/WEBNOIBO/Source/LICHCONGTAC/images\\\\order_down.gif
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|GENERATOR Microsoft\\ FrontPage\\ 5.0 ProgId FrontPage.Editor.Document HTTP-EQUIV=Content-Type text/html;\\ charset=UTF-8
vti_charset:SR|utf-8
vti_progid:SR|FrontPage.Editor.Document
vti_generator:SR|Microsoft FrontPage 5.0
vti_title:SR|Dang ky lich cong tac tuan
vti_backlinkinfo:VX|WEBNOIBO/Source/LICHCONGTAC/CAL_WEEK_WaitApprove.asp WEBNOIBO/Source/LICHCONGTAC/LichCongTac.asp
