vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|15 Feb 2005 04:25:18 -0000
vti_extenderversion:SR|6.0.2.5516
vti_backlinkinfo:VX|WEBNOIBO/Source/LICHCONGTAC/CAL_WEEK_WaitApprove.asp WEBNOIBO/Source/LICHCONGTAC/LichTrucLe_List.asp WEBNOIBO/Source/LICHCONGTAC/LichTruc_List.asp WEBNOIBO/Source/LICHCONGTAC/LICHTRUCLE_APPROVED.asp WEBNOIBO/Source/LICHCONGTAC/CAL_WEEK_APPROVED.asp WEBNOIBO/Source/LICHCONGTAC/CAL_Week_List.asp WEBNOIBO/Source/LICHCONGTAC/LICHTRUC_APPROVED.asp
